import 'package:food/Screens/Cart/item_model.dart';

List<Item> productsTIK = [
  Item(
      name: 'Veg Burger',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Tapri IITians Ki',
      itemdescription: '',
      identity: 'TPIK',
      price: 100,
      image: 'assets/images/pbm.jpg'),
  Item(
      name: 'Garlic Bread',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Tapri IITians Ki',
      itemdescription: '',
      identity: 'TPIK',
      price: 30,
      image: 'assets/images/kathiroll.jpg'),
  Item(
      name: 'Pav Bhaji',
      category: 'Veg',
      menutype: 'Fast Food',
      identity: 'TPIK',
      restaurant: 'Tapri IITians Ki',
      itemdescription: '',
      price: 25,
      image: 'assets/images/noodles.png'),
  Item(
      name: 'Grilled Sandwich',
      category: 'Veg',
      menutype: 'Fast Food',
      identity: 'TPIK',
      restaurant: 'Tapri IITians Ki',
      itemdescription: '',
      price: 8,
      image: 'assets/images/frenchfries.jpg'),
  Item(
      name: 'Red Sauce Pasta',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Tapri IITians Ki',
      itemdescription: '',
      identity: 'TPIK',
      price: 25,
      image: 'assets/images/coffee.jpg'),
  Item(
      name: 'White Sauce Pasta',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Tapri IITians Ki',
      itemdescription: '',
      identity: 'TPIK',
      price: 70,
      image: 'assets/images/cheesecornmomos.jpg'),
  Item(
      name: 'Bread Butter',
      category: 'Veg',
      menutype: 'Breakfast',
      restaurant: 'Tapri IITians Ki',
      itemdescription: '',
      identity: 'TPIK',
      price: 50,
      image: 'assets/images/grilledsandwich.jpg'),
  Item(
      name: 'Mojito',
      category: 'Veg',
      menutype: 'Beverages',
      restaurant: 'Tapri IITians Ki',
      itemdescription: '',
      identity: 'TPIK',
      price: 40,
      image: 'assets/images/paneerparatha.jpg'),
  Item(
      name: 'Paneer Tikka',
      category: 'Veg',
      menutype: 'Main Course',
      restaurant: 'Tapri IITians Ki',
      itemdescription: '',
      identity: 'TPIK',
      price: 12,
      image: 'assets/images/paneertikka.png'),
  Item(
      name: 'Pizza',
      category: 'Veg',
      menutype: 'Fast Food',
      restaurant: 'Tapri IITians Ki',
      itemdescription: '',
      identity: 'TPIK',
      price: 55,
      image: 'assets/images/pizza.png'),
];
